# Generated by Django 2.2.7 on 2019-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191123_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebranch',
            name='name',
            field=models.CharField(default='Holmes Home', max_length=1024, verbose_name='Name'),
        ),
    ]
