# Generated by Django 2.2.7 on 2019-11-27 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtokenauth',
            name='host_email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementtokenauth',
            name='token_given',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementtokenauth',
            name='token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='managementtokenauth',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'user_type': 'management'}, on_delete=django.db.models.deletion.CASCADE, related_name='management_token_auths', to=settings.AUTH_USER_MODEL),
        ),
    ]
