# Generated by Django 2.2.7 on 2019-11-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'visit', 'verbose_name_plural': 'visits'},
        ),
    ]
