# Generated by Django 2.2.7 on 2019-11-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20191120_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='host',
            field=models.ForeignKey(limit_choices_to={'user_type': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='host_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
