# Generated by Django 2.2.7 on 2019-11-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20191127_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementtokenauth',
            name='token_given',
            field=models.CharField(max_length=100),
        ),
    ]
