# Generated by Django 2.2.7 on 2019-11-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20191120_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
