# Generated by Django 2.2.7 on 2019-11-25 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20191123_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
