# Generated by Django 2.2.7 on 2019-11-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191123_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebranch',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
    ]
